package com.test.mapper;

import com.test.model.Test;

import java.util.List;
import java.util.Map;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    Test selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    int updateByPrimaryKeySelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    int updateByPrimaryKey(Test record);

    List<Test> getTests(Map paramMap);

    int getTestsCount(Map paramMap);
    void addTest(Test test);
    void editTest(Test test);
    void delTest(Integer id);

    Test getTestById(Integer id);
}