package com.test.model;

import java.util.Date;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.type
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.create_date
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.update_date
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.type
     *
     * @return the value of test.type
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.type
     *
     * @param type the value for test.type
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.create_date
     *
     * @return the value of test.create_date
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.create_date
     *
     * @param createDate the value for test.create_date
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.update_date
     *
     * @return the value of test.update_date
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.update_date
     *
     * @param updateDate the value for test.update_date
     *
     * @mbggenerated Tue Nov 12 23:51:09 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}